server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp12795f9jpeylrl5125010fm.mysql.rds.aliyuncs.com:3306/mylog?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&characterSetResults=utf8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: skz
    password: root1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    type-aliases-package: com.skz.springboot.mylog.entity

    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

    logging:
      level:
        root: warn
        com.skz: info
      file: log/blog-pro.log
